import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-skilled-nursing-pdpm-reimbursement-integrity",
  "engine": "recovery",
  "title": "Skilled Nursing PDPM Reimbursement Integrity",
  "shortTitle": "Skilled Nursing PDPM Reimbursement Integrity",
  "tagline": "Quantify, recover, and prevent financial leakage through skilled nursing pdpm reimbursement integrity",
  "industry": "Skilled Nursing Revenue Integrity",
  "uiPort": 4595,
  "apiPort": 5595,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Skilled Nursing PDPM Reimbursement Integrity converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Medicare Paid Amount",
    "expectedLabel": "PDPM-Supported Amount",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Skilled Nursing PDPM Reimbursement Integrity evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("resident-and-stay-registry","SNP01","Resident and stay registry","Execute resident and stay registry using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed resident and stay registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Resident and stay registry Reference","text","SNP01-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("mds-assessment-ingestion","SNP02","MDS assessment ingestion","Execute mds assessment ingestion using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed mds assessment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","MDS assessment ingestion Reference","text","SNP02-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("icd-10-category-mapping","SNP03","ICD-10 category mapping","Execute icd-10 category mapping using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed icd-10 category mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","ICD-10 category mapping Reference","text","SNP03-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("pt-component-calculation","SNP04","PT component calculation","Execute pt component calculation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed pt component calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","PT component calculation Reference","text","SNP04-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("ot-component-calculation","SNP05","OT component calculation","Execute ot component calculation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed ot component calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","OT component calculation Reference","text","SNP05-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("slp-component-calculation","SNP06","SLP component calculation","Execute slp component calculation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed slp component calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","SLP component calculation Reference","text","SNP06-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("nursing-component-calculation","SNP07","Nursing component calculation","Execute nursing component calculation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed nursing component calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Nursing component calculation Reference","text","SNP07-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("nta-component-calculation","SNP08","NTA component calculation","Execute nta component calculation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed nta component calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","NTA component calculation Reference","text","SNP08-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("variable-per-diem-adjustment","SNP09","Variable per-diem adjustment","Execute variable per-diem adjustment using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed variable per-diem adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Variable per-diem adjustment Reference","text","SNP09-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("interrupted-stay-validation","SNP10","Interrupted-stay validation","Execute interrupted-stay validation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed interrupted-stay validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Interrupted-stay validation Reference","text","SNP10-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("hiv-aids-adjustment","SNP11","HIV AIDS adjustment","Execute hiv aids adjustment using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed hiv aids adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","HIV AIDS adjustment Reference","text","SNP11-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("consolidated-billing-control","SNP12","Consolidated billing control","Execute consolidated billing control using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed consolidated billing control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Consolidated billing control Reference","text","SNP12-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("vbp-adjustment","SNP13","VBP adjustment","Execute vbp adjustment using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed vbp adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","VBP adjustment Reference","text","SNP13-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("claim-reconciliation","SNP14","Claim reconciliation","Execute claim reconciliation using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed claim reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Claim reconciliation Reference","text","SNP14-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]}),
feature("facility-reimbursement-analytics","SNP15","Facility reimbursement analytics","Execute facility reimbursement analytics using resident stays, MDS assessments, diagnoses, PDPM mappings, clinical components, interrupted stays, consolidated billing, claims, VBP adjustments, and remittances.","Produce a governed facility reimbursement analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Resident Stay","text","Facility / Resident Stay · Standard Case"],["caseReference","Facility reimbursement analytics Reference","text","SNP15-2026-001"],["paidAmount","Medicare Paid Amount","currency",494000],["expectedAmount","PDPM-Supported Amount","currency",582920],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Resident and stay registry case","MDS assessment ingestion case","ICD-10 category mapping case","PT component calculation case","OT component calculation case"]})
]);
